# Generated by Django 4.1.1 on 2022-09-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="user_id",
            new_name="user",
        ),
    ]
